# Dependencies
markdown:         kramdown
highlighter:      rouge

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

paginate: 5

plugins: [jekyll-paginate]



# Setup
title:            fri3nds
tagline:          'A craftsman typing carefully'
description:      'Here is my personal weblog about technology and life.'
url:              http://shelldone.com

author:
  name:           'fri3nds'
  url:            https://github.com/xiaoDC


# Custom vars
version:          1.0.0
